---
title: "**Long-term trends in melanoma tumour thickness in Norway**"
output: 
  github_document: default
  officedown::rdocx_document:
    reference_docx: Readme-Template.docx
---

<!-- 7632  -->

Hi, my name is Raju and I come from Oslo Center for Biostatistics and Epidemiology at the University of Oslo. The poster I am presenting is on the long-term trends in melanoma tumour thickness in Norway. This project is funded by the Norwegian Research Council and UNIFOR-FRIMED.

Tumour thickness is the primary determinant of T-category in Tumour-Node-Metastasis staging system and most important prognostic factor. Investigating long-term trends in tumour thickness and corresponding T-categories is the primary aim of this research. Using 47,439 morphologically verified first primary invasive melanoma cases from 1980 to 2019, the analysis is performed in the complete case series and in important subgroups such as sex, age and anatomic sites.

The first table shows that median age at diagnosis increased in both men and women over the study period. Table 2 shows that women were diagnosed at a thinner stage than men during this period. People in the oldest age group, 61-85, has the largest proportion of the thick cases. This we can also see in Figure 2. The same table also show that the median tumour thickness has decreased over time. Both men and women were diagnosed at a thinner stage in the recent years than before. 

T1-categories covers more than 50% of the total cases in women and 40% cases in men. The proportion of T1 has increased over time. The proportions the cases diagnosed as T2, T3 and T4 were comparatively more constant than T1. However, Figure 1 shows a slight decreasing trend in thicker cases (T3 and T4) in the recent years.
The trend of the proportion of the cases grouped by T-category, gender and anatomic sites is presented in Figure 3. Here, thin melanoma cases are the most common in all anatomic sites. The proportion of T1 showed a clear increase in the recent years for head/neck and upper limbs in men, and trunk and lower limbs in both men and women.  

I hope you have enjoyed this poster. This is a joint work of researchers from University of Oslo, Oslo University Hospital, the Cancer registry of Norway, QIMR Berghofer Medical Research Institute, and IARC. Thank you for your time.
